title: Zhou ShangLi's Homepage
page-top-title: Zhou ShangLi
top-section-bg-text: Computer Science
home-subtitle: Zhou ShangLi&ensp;|&ensp;周尚礼
copyright-text: '&copy; Zhou ShangLi 2023-2025. All Rights Reserved.'
